export const UPDATE_ACCOUNT_INFO = 'UPDATE_ACCOUNT_INFO';
export const UPDATE_MESSAGES = 'UPDATE_MESSAGES';
export const UPDATE_SIGN_STATUS = 'UPDATE_SIGN_STATUS';
export const UPDATE_NEWS = 'UPDATE_NEWS';
export const ROUND_TRIP_INFO = 'ROUND_TRIP_INFO';
export const ONE_WAY_INFO = 'ONE_WAY_INFO';
export const OPEN_JAW_INFO = 'OPEN_JAW_INFO';
export const ACTIVE_JOURNEY_TYPE = 'ACTIVE_JOURNEY_TYPE';

export const EXCHANGE_SEARCH_INFO = 'EXCHANGE_SEARCH_INFO';
